version: "3.7"

services:
  flask-api:
    image: medtrainer/app-name:dev
    container_name: app-name
    build:
      target: dev
    volumes:
      - .:/app
    ports:
      - 5678:5678
    environment:
      - DEBUG_MODE=1
      - ENVIRONMENT=development
    entrypoint: [ "python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "-m", "commands", "to", "run", "app" ]

