version: "3.7"

services:
  flask-api:
    image: medtrainer/app-name
    container_name: app-name
    build:
      context: .
      dockerfile: docker/python/Dockerfile
      target: dev
    ports:
      - 5000:5000
    networks:
      - app-network
    env_file:
      - .env.dist

networks:
  app-network:
    name: app-network
